### ISSUE TITLE
Requesting dataset: oral2

### ISSUE THREAD

**Issue by harshithshankar13** [MarcoParola/oral_segmentation#2]
I came across this GitHub repository and am particularly interested in the oral2 dataset that you have mentioned/used in your project. I believe that this dataset would be incredibly valuable for my work. Could you kindly provide a link to where I can access the dataset?

**Comment by MarcoParola** [comment]
Hi Harshith, thanks for your interest. We can discuss this by e-mail and I will close the issue on github. Here my mail: marco.parola@ing.unipi.it
